var sourcesIndex = JSON.parse('{\
"anyhow":["",[],["backtrace.rs","chain.rs","context.rs","ensure.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","ptr.rs","wrapper.rs"]],\
"ash":["",[["extensions",[["experimental",[],["amd.rs","mod.rs"]],["ext",[],["buffer_device_address.rs","calibrated_timestamps.rs","debug_marker.rs","debug_report.rs","debug_utils.rs","extended_dynamic_state.rs","extended_dynamic_state2.rs","full_screen_exclusive.rs","headless_surface.rs","metal_surface.rs","mod.rs","physical_device_drm.rs","private_data.rs","tooling_info.rs"]],["khr",[],["acceleration_structure.rs","android_surface.rs","buffer_device_address.rs","copy_commands2.rs","create_render_pass2.rs","deferred_host_operations.rs","display.rs","display_swapchain.rs","draw_indirect_count.rs","dynamic_rendering.rs","external_fence_fd.rs","external_fence_win32.rs","external_memory_fd.rs","external_memory_win32.rs","external_semaphore_fd.rs","external_semaphore_win32.rs","get_memory_requirements2.rs","get_physical_device_properties2.rs","get_surface_capabilities2.rs","maintenance1.rs","maintenance3.rs","maintenance4.rs","mod.rs","pipeline_executable_properties.rs","present_wait.rs","push_descriptor.rs","ray_tracing_pipeline.rs","surface.rs","swapchain.rs","synchronization2.rs","timeline_semaphore.rs","wayland_surface.rs","win32_surface.rs","xcb_surface.rs","xlib_surface.rs"]],["mvk",[],["ios_surface.rs","macos_surface.rs","mod.rs"]],["nn",[],["mod.rs","vi_surface.rs"]],["nv",[],["device_diagnostic_checkpoints.rs","mesh_shader.rs","mod.rs","ray_tracing.rs"]]],["mod.rs"]],["vk",[],["aliases.rs","bitflags.rs","const_debugs.rs","constants.rs","definitions.rs","enums.rs","extensions.rs","feature_extensions.rs","features.rs","macros.rs","native.rs","platform_types.rs","prelude.rs"]]],["device.rs","entry.rs","instance.rs","lib.rs","prelude.rs","util.rs","vk.rs"]],\
"ccthw_ash_allocator":["",[["allocation_requirements",[],["dedicated_resource_handle.rs","mod.rs"]],["memory_allocator",[],["composable_allocator.rs","device_allocator.rs","mod.rs"]]],["allocation.rs","error.rs","lib.rs","memory_properties.rs","pretty_wrappers.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"indoc":["",[],["error.rs","expr.rs","lib.rs","unindent.rs"]],\
"libloading":["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"proc_macro2":["",[],["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"syn":["",[["gen",[],["clone.rs","gen_helper.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]],\
"thiserror":["",[],["aserror.rs","display.rs","lib.rs"]],\
"thiserror_impl":["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]]\
}');
createSourceSidebar();
